[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "/badges/*"
  to = "https://cdn.frankerfacez.com/94/7f/947f5a8228c906ddfa20589800b19276.png"
  status = 301
